// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7a2le05ViLV-UeYU6Q3V3rah4jxCdsjo',
    appId: '1:276858134837:web:2cb803dc93be17d66dac7c',
    messagingSenderId: '276858134837',
    projectId: 'zuriwebapp-60676',
    authDomain: 'zuriwebapp-60676.firebaseapp.com',
    storageBucket: 'zuriwebapp-60676.firebasestorage.app',
    measurementId: 'G-F450E0YDMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt5Rh-9_4hIZK1buUjw23zxXwEep38qA8',
    appId: '1:276858134837:android:f0957650245b02a76dac7c',
    messagingSenderId: '276858134837',
    projectId: 'zuriwebapp-60676',
    storageBucket: 'zuriwebapp-60676.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQucJzNsPBO_6pgkoTjCmo93uwA9ELsU',
    appId: '1:276858134837:ios:ddb2e24749bfbaf56dac7c',
    messagingSenderId: '276858134837',
    projectId: 'zuriwebapp-60676',
    storageBucket: 'zuriwebapp-60676.firebasestorage.app',
    iosBundleId: 'com.example.testing2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQQucJzNsPBO_6pgkoTjCmo93uwA9ELsU',
    appId: '1:276858134837:ios:ddb2e24749bfbaf56dac7c',
    messagingSenderId: '276858134837',
    projectId: 'zuriwebapp-60676',
    storageBucket: 'zuriwebapp-60676.firebasestorage.app',
    iosBundleId: 'com.example.testing2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7a2le05ViLV-UeYU6Q3V3rah4jxCdsjo',
    appId: '1:276858134837:web:673923161337a54f6dac7c',
    messagingSenderId: '276858134837',
    projectId: 'zuriwebapp-60676',
    authDomain: 'zuriwebapp-60676.firebaseapp.com',
    storageBucket: 'zuriwebapp-60676.firebasestorage.app',
    measurementId: 'G-FEY6FWHGMP',
  );
}
